### ISSUE TITLE
Comentarios portafolio

### ISSUE THREAD

**Issue by FabianBravoA** [VeronicaManchola/VeronicaManchola.github.io#1]
Diseño limpio y directo. Funciona bien en diferentes tamaños de pantalla.
Podrías darle un poco más de tu toque al diseño, ya que puede ser demasiado formal y no combina mucho con los íconos de la sección de contacto. Pero esto es solo si tienes tiempo ya que, como escribí, está super bien tu portafolio y es solo para que sea aun mejor.

**Comment by VeronicaManchola** [comment]
Version final contiene una pagina de opcion de idioma que la hace mas dinamica. Tambien se agregó un about me y una animación on hover a los botones de contacto para hacerlos mas llamativos.
